### PR TITLE
cli: add sound when awaiting ledger interaction

### PR DESCRIPTION
**Pull request by juliangruber**
Since it's a long running script, notify the operator that a ledger interaction is necessary

### CODE REVIEW

**Review by bajtos — APPROVED** [review]
The changes SGTM, with two comments to consider:

- Personally, I configured my terminal to turn ANSI beep sequence into a screen flash, so this is probably not going to work for me. (I didn't check, TBH.)
- In the past, I had a good experience using `say`, a built-in macOS CLI utility. That may not be portable to Linux/Windows, though.

**Comment by juliangruber** [comment]
> The changes SGTM, with two comments to consider:
> 
> * Personally, I configured my terminal to turn ANSI beep sequence into a screen flash, so this is probably not going to work for me. (I didn't check, TBH.)

Beeper uses this:

```js
process.stdout.write('\u0007');
```

Can you try if that creates a sound for you? For me it plays a sound and makes the screen flash.

> * In the past, I had a good experience using `say`, a built-in macOS CLI utility. That may not be portable to Linux/Windows, though.

I'm also using that in my shall, eg `node script.js && say "done"`, but that doesn't work here (unless we add something like `node script.js --on-ledger="say \"attention\""`). I could look into a `say` node module (for a portable solution), or would you suggest to just spawn that utility?

**Comment by bajtos** [comment]
> > The changes SGTM, with two comments to consider:
> > 
> > * Personally, I configured my terminal to turn ANSI beep sequence into a screen flash, so this is probably not going to work for me. (I didn't check, TBH.)
> 
> Beeper uses this:
> 
> ```js
> process.stdout.write('\u0007');
> ```
> 
> Can you try if that creates a sound for you? For me it plays a sound and makes the screen flash.

```bash
node -e "process.stdout.write('\u0007');"
```

For me, this flashes the screen, but there is no sound.

> > * In the past, I had a good experience using `say`, a built-in macOS CLI utility. That may not be portable to Linux/Windows, though.
> 
> I'm also using that in my shall, eg `node script.js && say "done"`, but that doesn't work here (unless we add something like `node script.js --on-ledger="say \"attention\""`). I could look into a `say` node module (for a portable solution), or would you suggest to just spawn that utility?

IDK, TBH. I don't want us to spend too much time on this, it does not seem to worth the effort.

What is the simplest solution?

How about we execute the `say` CLI when running on macOS and fall back to beeper on other platforms? (We can use your `write` snippet directly to avoid an extra dependency.)

**Comment by bajtos** [comment]
We can also land this PR as-is and improve it iteratively later.

**Comment by juliangruber** [comment]
Up to you! I'm fine with the solution as is because it does everything I need. I propose you follow up with a `say` implementation if you need it?

**Comment by juliangruber** [comment]
I would say it's fair to assume that a shell ascii beep works, and I think your setup diverges from the norm, therefore I think following up with `say` best sits with you

**Comment by bajtos** [comment]
SGTM 👌🏻

**Pull request merged**
